sudo: required
services:
  - docker

before_install:
  - docker build -t evelynle/docker-react  -f Dockerfile.dev .

script:
  - docker run evelynle/docker-react npm run test -- --coverage

